#ifndef PONEDM_BOT_H
#define PONEDM_BOT_H

#ifdef _WIN32
#pragma once
#endif

#include "bots\bot.h"
#include "ai_hint.h"

//JESUS CHRIST!!!!
static const char* m_botPonyNames[] =
{
    "Autumn",
    "Brilliant",
    "Citrus",
    "Cloudy",
    "Cool",
    "Creamy",
    "Curly",
    "Dreamy",
    "Dusty",
    "Fancy",
    "Frilly",
    "Frosty",
    "Ginger",
    "Lacy",
    "Lucky",
    "Lovely",
    "Merry",
    "Midnight",
    "Minty",
    "Morning",
    "Night",
    "Ocean",
    "Peachy",
    "Precious",
    "Pretty",
    "River",
    "Rosie",
    "Royal",
    "Sea",
    "Silky",
    "Sky",
    "Snazzy",
    "Speedy",
    "Spring",
    "Stormy",
    "Summer",
    "Sunny",
    "Sweetie",
    "Tropical",
    "Whirly",
    "Wild",
    "Windy",
    "Winter",
    "Amber",
    "Amethyst",
    "Angel",
    "Apple",
    "Apricot",
    "Aqua",
    "Azure",
    "Banana",
    "Beach",
    "Beauty",
    "Bell",
    "Berry",
    "Blue",
    "Blueberry",
    "Bright",
    "Bubble",
    "Butter",
    "Candy",
    "Caramel",
    "Cream",
    "Cherry",
    "Cherries",
    "Cinnamon",
    "Cloud",
    "Cocoa",
    "Comet",
    "Cookie",
    "Coral",
    "Cotton",
    "Cream",
    "Crimson",
    "Crunch",
    "Crystal",
    "Daffodil",
    "Dahlia",
    "Daisy",
    "Dawn",
    "Dewdrop",
    "Diamond",
    "Emerald",
    "Fairy",
    "Feather",
    "Flip",
    "Fire",
    "Flitter",
    "Flower",
    "Flutter",
    "Frost",
    "Glimmer",
    "Glitter",
    "Gold",
    "Harmony",
    "Holly",
    "Honey",
    "Huckleberry",
    "Indigo",
    "Jewel",
    "Lavender",
    "Lemon",
    "Lemonade",
    "Light",
    "Lilac",
    "Lily",
    "Lime",
    "Love",
    "Magenta",
    "Magic",
    "Mango",
    "Maple",
    "Marigold",
    "Melody",
    "Meringue",
    "Mint",
    "Moon",
    "Moonlight",
    "Muffin",
    "Onyx",
    "Opal",
    "Orange",
    "Peach",
    "Pearl",
    "Pepper",
    "Peridot",
    "Petal",
    "Pineapple",
    "Pink",
    "Plum",
    "Poppy",
    "Posey",
    "Prince",
    "Princess",
    "Pumpkin",
    "Rain",
    "Rainbow",
    "Raspberry",
    "Red",
    "Rose",
    "Rouge",
    "Ruby",
    "Sapphire",
    "Satin",
    "Scarlet",
    "Secret",
    "Shadow",
    "Shimmer",
    "Silk",
    "Silver",
    "Snow",
    "Sparkle",
    "Spice",
    "Star",
    "Strawberry",
    "Sugar",
    "Sun",
    "Sunset",
    "Sunshine",
    "Sweet",
    "Taffy",
    "Tangerine",
    "Tangy",
    "Tulip",
    "Twilight",
    "Twinkle",
    "Velvet",
    "Wind",
    "Wing",
    "Beam",
    "Blaze",
    "Bloom",
    "Blossom",
    "Bow",
    "Bunch",
    "Breeze",
    "Burst",
    "Cake",
    "Chaser",
    "Crisp",
    "Dancer",
    "Dash",
    "Dasher",
    "Dazzle",
    "Dazzler",
    "Delight",
    "Dreamer",
    "Dreams",
    "Drop",
    "Dust",
    "Eyes",
    "Fizz",
    "Flake",
    "Flash",
    "Frills",
    "Glory",
    "Glow",
    "Heart",
    "Joy",
    "Jubilee",
    "Lace",
    "Mist",
    "Pie",
    "Puff",
    "Ribbon",
    "Sherbet",
    "Shine",
    "Shore",
    "Shores",
    "Skimmer",
    "Skipper",
    "Snap",
    "Song",
    "Splash",
    "Spray",
    "Surprise",
    "Swirl",
    "Treat",
    "Twirl",
    "Twist",
    "Whirl",
    "Wish"
};

//================================================================================
// Artificial intelligence for PoneDM
//================================================================================
class CPoneDM_Bot : public CBot
{
public:
    DECLARE_CLASS_GAMEROOT(CPoneDM_Bot, CBot);

    CPoneDM_Bot(CBasePlayer* parent);

public:
    virtual void Spawn();
    virtual void Update();
    virtual void SetUpComponents();
    virtual void SetUpSchedules();
};

extern CPlayer* CreatePoneDMBot(const char* pPlayername, const Vector* vecPosition, const QAngle* angles);
void SpawnPoneDMBots(int botCount);

#endif // PONEDM_BOT_H